### PR TITLE
Updates to the Finnish translation

### PR DESCRIPTION
**Pull request by olavinto**
A lot of missing additions and some tweaking. Additionally, a few %1 variables that are used in place of FDM (or Free Download Manager) were replaced with actual text. In Finnish we MUST be able to inflect names too, even foreign ones, to be able to translate sentences correctly. Check out the following recourse for more information: https://uusikielemme.fi/finnish-grammar/finnish-cases/interesting-inflection/inflection-of-foreign-names-in-finnish

This does not change their meaning or make them obscure - instead it has the opposing effect and makes the text more fluent and natural to read.

However, how this affects (if at all) building the final language files is a separate topic and if this poses a problem, please notify me and I will try to somehow make the sentences work with these variables.

### CODE REVIEW

**Comment by FreeDownloadManagerTeam** [comment]
Why not just use %1xx instead?

For example, "Notify me of downloads only when %1 window is inactive" translate as "Ilmoita vain kun %1in ikkuna ei ole aktiivinen".

**Comment by FreeDownloadManagerTeam** [comment]
P.S. Is there any difference between "Free Download Manager" and "FDM"?
The above example uses "FDM". So is it OK for it to be translated as "Ilmoita vain kun FDMin ikkuna ei ole aktiivinen"?

**Comment by olavinto** [comment]
Shorthands like FDM are a bit problematic because they kind of break the flow and it is the main reason why I used the whole name for some of them. With FDM we would use :ending, e.q. Open link in FDM = avaa linkki FDM:ssä = Open link in Free Download Managerissa, and of these two the latter is more natural. Also, the change from -:ssä to -ssa happens due how they are pronunced. And these endings may vary more depending on the required form.

On an additional note, there are some strings where the app's name isn't required at all. I do not remember an exact example right now but let's use "Start FDM during system startup" as an example - it should be pretty evident to the user that the setting concerns the app they are currently using. It is kind of similar how television shows (at least US shows) like to repeat the characters names during ongoing conversations (despite the audience seeing them anyway...).

**Comment by FreeDownloadManagerTeam** [comment]
Dear user, unfortunately, we need these %1 to stay in place.
The only I can suggest is to just use %1xx as I mentioned above. But, you'll need to know if a short or long name is used in the each case. 
If you agree, I will give you the information regarding what exact form (short or long app name) is used in the each translated string.

**Comment by olavinto** [comment]
Yeah, that's fine. I can see most strings in the UI but things like notification/alarms/platform specific differences/ttc. might be difficult to find (I have all platforms for testing but I only actually use FDM on Windows). I will correct the strings I changed when I can (I can find those easily).

**Comment by FreeDownloadManagerTeam** [comment]
"Notify me of downloads only when %1 window is inactive" - short form is used (i.e. FDM).

"browser does not provide to %1 (or there is no universal way for all " - short form.

"Portable version of %1 can be used on different computers without the need " - long form.

"A bug report will be sent to the server and used to improve %1 performance." - short form.

"About %1" - long form.

"Download with %1", "Download all with %1", "Download selected with %1", "Download video with %1" - short form (yes, I'm sure).

"Allow remote access to %1 running on this device" - short form.

"What's new in %1" - %1 is not FDM name at all. It's its version. So please keep it as is.

"%1 is up to date" - short form.

"Relaunch %1 to update" - short form.

"Enjoy %1?" - short form.

**Comment by olavinto** [comment]
These could also be comments in the language files so that translators could see them.

**Comment by FreeDownloadManagerTeam** [comment]
> These could also be comments in the language files so that translators could see them.

Yeah. I just could not imagine (until recently) that it can be required in some languages...

**Comment by olavinto** [comment]
Yeah, that is understandable. Finnish is one of the more complex ones and it is very common to encounter situations like this - and this is very minor. There are some projects that are impossible to translate because localization hasn't been given enough attention - some languages require special consideration. FDM is generally fine in that regard.

**Pull request merged**
