### PR TITLE
Update Italian language

### PR DESCRIPTION
**Pull request by bovirus**
@FreeDownloadManagerTeam 

Please merge. Thanks.

### CODE REVIEW

**Comment by FreeDownloadManagerTeam** [comment]
Why new file?

**Comment by bovirus** [comment]
@FreeDownloadManagerTeam 

I have a system that check automatically the new language file and it found that you amde some changes to your files and you have some new strings (empty).

I beleieve that before to close a pull request at least you have to check your files.

Please check screenshots.

image

Pelase re-open the PR amnd merge file. Thanks.

**Comment by FreeDownloadManagerTeam** [comment]
You've created a new file fdm_it_main.po instead of modifying the existing one (fdm_it.po). So you want us to have an maintain two separate files instead of one?

**Comment by FreeDownloadManagerTeam** [comment]
Not true? :) 

Just check your repository (https://github.com/bovirus/FDM6-localization/tree/master/main) and compare it with the original one. 

You'll see that you have two files instead of one. 
1. Original file: https://github.com/bovirus/FDM6-localization/blob/master/main/fdm_it.po
2. The one you've added and trying to commit using this pull request: https://github.com/bovirus/FDM6-localization/blob/master/main/fdm_it_main.po.

So, could you please fix it?

**Pull request closed without merging**
