### PR TITLE
Added hi_IN (Hindi India) translations.

### PR DESCRIPTION
**Pull request by saumya-banthia**

### CODE REVIEW

**Comment by Prasanta-Hembram** [comment]
Hello @saumya-banthia @shelaf @MELERIX @xlcwu @bovirus ... It's seems like Hindi language was not accepted because the translations are not up to date....Please also make it clear in the readme file that you are not accepting new languages so that it will save time of hardworking translators who are willing to translate this software. I need a green flag from the freeDownloadManager Developers so that I can update translations for this language..Please comment..

**Comment by shelaf** [comment]
I don't know why the new language resources aren't accepted, but at least the current content is too old and won't be accepted unless these are updated.

**Comment by Prasanta-Hembram** [comment]
Thanks @shelaf for the reply, I will update and create a PR for the updated Hindi translation.

**Comment by FreeDownloadManagerTeam** [comment]
Hello,

Some translated strings are broken. Please make sure all "%1", "%2", etc. present and valid. 

For example: 

1) "An internal error occurred.<br>%1 needs to be restarted for further use."
msgstr "एक आंतरिक समस्या हुई है।<br>% 1 को आगे उपयोग के लिए पुनः शूरू करने की आवश्यकता है।"

There is space between % and 1, which is a error.

2) msgid "Restart %1 automatically"
msgstr "स्वचालित रूप से पुनः आरंभ करें"

I don't see %1 in the translated string.

**Comment by Prasanta-Hembram** [comment]
> Please make sure all \"%1\", \"%2\", etc. present and valid.

Hi, @FreeDownloadManagerTeam I think the previous translator hasn't used any CAT tools to translate. I will double check it and create a new pull request from the scratch soon.

**Pull request closed without merging**
