### PR TITLE
Update Italian language

### PR DESCRIPTION
**Pull request by bovirus**
@FreeDownloadManagerTeam 

Please merge.

It's very strange.
I already did the strings adding but in last your reposiory update I found many strings recently added cleared.

Thanks.

### CODE REVIEW

**Comment by FreeDownloadManagerTeam** [comment]
Any example of such a cleared string?

**Comment by bovirus** [comment]
@FreeDownloadManagerTeam 

Please compare in PR original strings and new strings.
You can see that some string in the original file are empty.
But I already sent you the files before with same strings that now empty before were translated and you approved the PR before.

Please merge my PR and in the future I will check again.

**Comment by FreeDownloadManagerTeam** [comment]
I can't help you until you give me an example.

**Comment by bovirus** [comment]
@FreeDownloadManagerTeam 

Why didn't get the PR content

**Comment by FreeDownloadManagerTeam** [comment]
Something must be wrong on your side. I've checked these strings - all is OK. Translated strings has never been erased for them.

**Comment by bovirus** [comment]
@FreeDownloadManagerTeam 

I have an automatic system that compare mny file with relative fiels on project on github.

Now is ok.
Pleasse close the ticket. 
Thanks.

**Pull request merged**
