### PR TITLE
Update Italian language

### PR DESCRIPTION
**Pull request by bovirus**
@FreeDownloadManagerTeam 

Please check and merge. Thanks.

### CODE REVIEW

**Comment by lychichem** [comment]
？
I am NOT the owner of the repository. I can only review your change. If you want someone to merge your commit, you should call FDMTeam.

**Comment by bovirus** [comment]
@lychichem 
I already uploaded in past Italian language

Who the user name of FDM team?

Thanks.

**Comment by bovirus** [comment]
@lychichem 

Thanks.
I changed in first post the user reference.

**Comment by KyrU85** [comment]
@bovirus
You keep editing random strings for no reason at all. Since months im doing the whole translation without ever add my name in .po file details; you did it! Aren't you ashamed about this?

**Comment by lychichem** [comment]
> @bovirus You keep editing random strings for no reason at all. Since months im doing the whole translation without ever add my name in .po file details; you did it! Aren't you ashamed about this?

I reviewed the files changed. Maybe he is not doing so on purpose, this should be a setting problem to his Poedit tool. It seems like automatically generated lines. @bovirus could you please change your Poedit seeting to not adding these lines, as @KyrU85 says?

**Comment by bovirus** [comment]
@KyrU85 
@lychichem

Thanks for the info.
I revised the language file and removed not necessary lines in the header.
The lines was added automaticaly by POEdit.

I beleive that could be useful to add in language file a line that contain language file vesrion and author to check it for next reviewers.

**Pull request merged**
